version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudStorage
    ports:
      - "5432:5432"
    volumes:
      - cloudStorage-db-data:/var/lib/postgresql/data

volumes:
  cloudStorage-db-data: